/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FindingsIndexRouteImport } from './routes/findings/index'
import { Route as SituationsIndexRouteImport } from './routes/situations/index'
import { Route as SituationsIdRouteImport } from './routes/situations/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsIndexRoute = FindingsIndexRouteImport.update({
  id: '/findings/',
  path: '/findings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationsIndexRoute = SituationsIndexRouteImport.update({
  id: '/situations/',
  path: '/situations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationsIdRoute = SituationsIdRouteImport.update({
  id: '/situations/$id',
  path: '/situations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/situations/$id': typeof SituationsIdRoute
  '/findings/': typeof FindingsIndexRoute
  '/situations/': typeof SituationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/situations/$id': typeof SituationsIdRoute
  '/findings': typeof FindingsIndexRoute
  '/situations': typeof SituationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/situations/$id': typeof SituationsIdRoute
  '/findings/': typeof FindingsIndexRoute
  '/situations/': typeof SituationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/situations/$id' | '/findings/' | '/situations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/situations/$id' | '/findings' | '/situations'
  id: '__root__' | '/' | '/situations/$id' | '/findings/' | '/situations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SituationsIdRoute: typeof SituationsIdRoute
  FindingsIndexRoute: typeof FindingsIndexRoute
  SituationsIndexRoute: typeof SituationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/': {
      id: '/findings/'
      path: '/findings'
      fullPath: '/findings/'
      preLoaderRoute: typeof FindingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situations/': {
      id: '/situations/'
      path: '/situations'
      fullPath: '/situations/'
      preLoaderRoute: typeof SituationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situations/$id': {
      id: '/situations/$id'
      path: '/situations/$id'
      fullPath: '/situations/$id'
      preLoaderRoute: typeof SituationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SituationsIdRoute: SituationsIdRoute,
  FindingsIndexRoute: FindingsIndexRoute,
  SituationsIndexRoute: SituationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
